# Generated by Django 4.1.4 on 2023-01-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
