# Generated by Django 4.1.4 on 2023-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
