# Generated by Django 4.1.4 on 2023-01-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_classify_product_classify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classify',
            name='category',
        ),
    ]
