# Generated by Django 4.1.4 on 2023-01-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_classify_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='core/static/assets'),
        ),
    ]
